[[pages]]
name = "Profile Settings"
icon = ""
is_section = true

[[pages]]
path = "./basic.py"
name = "Basic Information"
icon = "ğŸ“–"

[[pages]]
path = "./daeb.py"
name = "Diet and Eating Habits"
icon = "ğŸ¥"

[[pages]]
path = "./ba.py"
name = "Body Assessment"
icon = "ğŸ°"

[[pages]]
path = "./lifestyleInformation.py"
name = "life Style Information"
icon = "âœï¸"

[[pages]]
path = "./lifestyle_condition.py"
name = "lifeStyle Conditionn"
icon = "âš•ï¸"

[[pages]]
path = "./goal.py"
name = "Your Goal"
icon = """"


[[pages]]
path = "Profile.py"
name = "Profile"
icon = "ğŸ§°"
in_section = false