[[pages]]
name = "Profile Settings"
icon = ":Settings:"
is_section = true

[[pages]]
path = "basic.py"
name = "Basic Information"
icon = "ğŸ“–"

[[pages]]
path = "lifestyleInformation.py.py"
name = "life Style Information"
icon = "âœï¸"

[[pages]]
path = "Profile.py"
name = "Profile"
icon = "ğŸ§°"
in_section = false