[[pages]]
name = "Profile Settings"
icon = ""
is_section = true

[[pages]]
path = "./pages/basic.py"
name = "Basic Information"
icon = "ğŸ“–"

[[pages]]
path = "./pages/daeb.py"
name = "Diet and Eating Habits"
icon = "ğŸ¥"

[[pages]]
path = "./pages/ba.py"
name = "Body Assessment"
icon = "ğŸ°"

[[pages]]
path = "./pages/lifestyleInformation.py"
name = "life Style Information"
icon = "âœï¸"

[[pages]]
path = "./pages/lifestyle_condition.py"
name = "lifeStyle Conditionn"
icon = "âš•ï¸"

[[pages]]
path = "./pages/goal.py"
name = "Your Goal"
icon = "âš•ï¸"

[[pages]]
path = "./pages/Profile.py"
name = "Profile"
icon = "ğŸ§°"
in_section = false